spring.application.name=spring-demo
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/spring_demo
spring.datasource.username=athiselvam
spring.datasource.password=selvam2024

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true